#### statsmodel
통계 분석 전용 라이브러리
주요 기능으로 회귀 분석, 시계열 분석, 가설 검정

단순 선형 회귀

In [9]:
import statsmodels.api as sm

data = sm.datasets.get_rdataset("mtcars").data
print(data.head())

X = data['hp']
y = data['mpg']

X = sm.add_constant(X)

model = sm.OLS(y,X).fit()

print(model.summary())

                    mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  \
rownames                                                                     
Mazda RX4          21.0    6  160.0  110  3.90  2.620  16.46   0   1     4   
Mazda RX4 Wag      21.0    6  160.0  110  3.90  2.875  17.02   0   1     4   
Datsun 710         22.8    4  108.0   93  3.85  2.320  18.61   1   1     4   
Hornet 4 Drive     21.4    6  258.0  110  3.08  3.215  19.44   1   0     3   
Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3   

                   carb  
rownames                 
Mazda RX4             4  
Mazda RX4 Wag         4  
Datsun 710            1  
Hornet 4 Drive        1  
Hornet Sportabout     2  
                            OLS Regression Results                            
Dep. Variable:                    mpg   R-squared:                       0.602
Model:                            OLS   Adj. R-squared:                  0.589
Method:                 Least Squa

1. 기본 정보  
Dep. Variable: mpg 종속변수(y)가 mpg(연비)라는 뜻. 우리가 예측하고 싶은 값임. 독립변수(x)로 이 값을 얼마나 잘 설명할 수 있는지가 이 분석의 목적.

No. Observations: 32 분석에 사용된 데이터가 32개. 샘플이 적을수록 결과의 신뢰도가 낮아질 수 있음. 일반적으로 회귀분석은 독립변수 1개당 최소 10~20개 샘플이 권장됨. 여기선 독립변수 1개에 32개니까 적당한 수준.

Df Model: 1 모델에 사용된 독립변수가 1개라는 뜻. 독립변수가 늘어날수록 Df Model도 올라감.

Df Residuals: 30 32 - 1(독립변수) - 1(상수항) = 30. 잔차의 자유도. 통계 검정할 때 내부적으로 사용됨.

2. 설명력 지표  
R-squared: 0.602 결정계수라고 부름. 독립변수가 종속변수의 변동을 얼마나 설명하는지 나타내는 값. 0~1 사이이며 1에 가까울수록 좋음.

여기선 0.602니까 독립변수가 mpg 변동의 60.2%를 설명하고 있다는 뜻. 나머지 39.8%는 이 모델이 잡아내지 못한 다른 요인들(예: 차량 무게, 엔진 크기 등)에 의한 것.

R² = 0.602
→ 모델이 설명하는 부분: 60.2%  ✅  
→ 모델이 설명 못하는 부분: 39.8%  ← 다른 변수 추가 고려  
Adj. R-squared: 0.589   
R²의 문제점은 독립변수를 무조건 추가하면 의미없는 변수라도 R²이 올라간다는 것. 이걸 보정한 게 수정 결정계수(Adjusted R²) 임. 독립변수의 개수가 많아지면 결정계수의 값이 증가하는 문제를 해결하기 위해 독립변수의 개수와 표본 크기를 고려하여 결정계수를 조정한 값.

R²      = 0.602  ← 변수 추가할수록 무조건 올라감  
Adj. R² = 0.589  ← 의미없는 변수 추가하면 오히려 내려감  
변수가 1개뿐이라 두 값의 차이가 크지 않지만, 변수가 많아질수록 이 차이가 커짐. 모델 비교할 땐 Adj. R²을 보는 게 더 정확함.

3. 모델 유의성 검정  
F-statistic: 45.46  
"이 모델 전체가 의미있냐?" 를 검정하는 값. 쉽게 말하면 독립변수들이 종속변수를 설명하는 데 아무 쓸모가 없다(귀무가설) 는 걸 기각할 수 있는지 확인하는 것.  
전체 회귀모델이 통계적으로 유의한지 검정하기 위해 사용되는 값.  
값이 클수록 모델이 유의하다는 증거가 강함. 45.46은 꽤 큰 값.  
F 값은 회귀모델의 전체적인 유의성을 평가하며, 반면 각 독립변수의 개별적인 영향력을 t-통계량을 사용하여 검정

Prob (F-statistic): 1.79e-07  
F통계량의 p값.  
회귀분석 모델 전체에 대한 통계적 의미 판단(0.05 이하인 경우 독립변수 유의미)
1.79e-07 = 0.000000179로 사실상 0에 가까움.  

p값 < 0.05  → 모델이 통계적으로 유의함  ✅  
p값 > 0.05  → 모델이 통계적으로 유의하지 않음  ❌  

여기선 0.000000179 << 0.05  → 매우 강하게 유의함 ✅
즉 "독립변수가 mpg를 설명하는 데 아무 의미없다"는 가설을 강하게 기각할 수 있음.

4. 모델 품질 비교 지표  
Log-Likelihood: -87.619 모델이 데이터를 얼마나 잘 설명하는지를 로그 확률로 나타낸 값. 0에 가까울수록(음수에서 올라갈수록) 좋음. 단독으로 해석하기보단 다른 모델과 비교할 때 씀.

AIC: 179.2 / BIC: 182.2  
AIC: 표본의 개수와 모델의 복잡성을 기반으로 모델을 평가하며, 수치가 낮을 수록 좋음
BIC: AIC와 유사하나 패널티를 부여하여 AIC보다 모델 평가 성능이 더 좋으며, 수치가 낮을 수록 좋음  
둘 다 모델 복잡도에 패널티를 부여한 지표. 변수를 많이 추가해도 성능이 좋아지지 않으면 값이 올라감.

AIC = -2 × Log-Likelihood + 2 × 변수수  
BIC = -2 × Log-Likelihood + log(n) × 변수수  
낮을수록 좋은 모델  
여러 모델을 만들어보고 AIC/BIC가 가장 낮은 모델을 선택하는 방식으로 활용  
BIC는 AIC보다 변수 수에 더 강한 패널티를 부여 → 더 단순한 모델을 선호하는 경향  

coef(coefficient, 회귀계수)  
데이터로부터 얻은 계수(절편, 기울기)의 추정치

std err  
계수 추정치의 표준오차(standard error), 값이 작을 수록 좋음
t  
t-검정(test), 독립변수와 종속변수 사이의 상관관계, 값이 클 수록 상관도가 큼

P>[t]
p-값(value)  
회귀 계수가 통계적으로 유의미한지 표시(0.05보다 작을 경우 유의미)
p는 독립 변수가 종속 변수에 유의미한 영향을 미칠 확률

5. 종합 결론  
✅ 모델 유의성: p = 1.79e-07 → 매우 강하게 유의함  
✅ 설명력: R² = 0.602 → 60% 설명 가능, 나쁘지 않은 수준  
⚠️ 한계: 40%는 설명 못함 → 독립변수 추가 고려 필요  
독립변수 1개만으로 mpg의 60%를 설명하고 있으니 꽤 강한 관계가 있는 변수를 사용한 것. 하지만 실제 연비는 차량 무게, 배기량, 실린더 수 등 다양한 요인이 영향을 주기 때문에 변수를 추가하면 설명력이 더 올라갈 가능성이 높음.

다중 선형 회귀

In [14]:
# import statsmodels.api as sm

# data = sm.datasets.get_rdataset("mtcars").data

X = data[['hp', 'wt']]
y = data['mpg']

X = sm.add_constant(X) # 독립 변수에 상수항(절편)을 추가

model = sm.OLS(y, X).fit()

print(model.summary())

                            OLS Regression Results                            
Dep. Variable:                    mpg   R-squared:                       0.827
Model:                            OLS   Adj. R-squared:                  0.815
Method:                 Least Squares   F-statistic:                     69.21
Date:                Thu, 12 Mar 2026   Prob (F-statistic):           9.11e-12
Time:                        10:33:37   Log-Likelihood:                -74.326
No. Observations:                  32   AIC:                             154.7
Df Residuals:                      29   BIC:                             159.0
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         37.2273      1.599     23.285      0.0

OLS 회귀분석 결과 해석  
1. 기본 정보  
Dep. Variable: mpg  
종속변수(우리가 예측하려는 값)는 mpg (연비)  

Model: OLS  
사용한 모델은 OLS (Ordinary Least Squares, 최소제곱법)  
→ 실제값과 예측값의 차이(오차)를 최소화하는 직선을 찾는 방법  

No. Observations: 32  
데이터 샘플 수는 32개  

2. 모델 성능 지표  
R-squared: 0.827  
결정계수. 모델이 데이터를 얼마나 잘 설명하는지를 나타냄  
→ hp와 wt 두 변수가 mpg 변동의 82.7%를 설명함  
→ 1에 가까울수록 좋고, 0.8 이상이면 꽤 좋은 모델  

Adj. R-squared: 0.815  
변수 개수를 고려해서 보정한 R-squared  
→ 변수를 무작정 늘리면 R-squared는 올라가는데, 이를 패널티로 보정한 값  
→ R-squared랑 큰 차이 없으면 변수 수가 적절하다는 의미  

F-statistic: 69.21 / Prob: 9.11e-12  
모델 전체가 통계적으로 유의미한지 검정  
→ Prob가 0.05보다 훨씬 작으므로 모델 자체가 유의미함  
→ "hp, wt 두 변수를 합쳐서 쓰는 게 의미 있다"는 뜻  

3. 회귀 계수 해석 (핵심)  
                 coef    std err          t      P>|t|  
const         37.2273      1.599     23.285      0.000  
hp            -0.0318      0.009     -3.519      0.001  
wt            -3.8778      0.633     -6.129      0.000  
회귀식으로 표현하면:  

mpg = 37.2273 + (-0.0318 × hp) + (-3.8778 × wt)  

const: 37.2273  
절편(intercept). hp=0, wt=0일 때 mpg의 기댓값  
→ 현실적인 의미보단 수식의 기준점 역할  

hp(마력): -0.0318  
hp가 1 증가하면 mpg가 0.0318 감소  
→ 마력이 높을수록 연비가 약간 떨어짐    
→ P>|t| = 0.001 → 통계적으로 유의미함 (0.05 이하)   

wt(무게): -3.8778   
wt가 1 증가하면 mpg가 3.8778 감소   
→ 무게가 증가할수록 연비가 크게 떨어짐  
→ P>|t| = 0.000 → 통계적으로 매우 유의미함  
→ hp보다 wt의 영향이 훨씬 큼    

P>|t| (p-value) 기준:   

p < 0.05   → 유의미함  ✅   
p >= 0.05  → 유의미하지 않음 ❌ 
[0.025, 0.975] (95% 신뢰구간):  

hp:  [-0.050, -0.013]  → 0을 포함하지 않음 → 유의미 ✅  
wt:  [-5.172, -2.584]  → 0을 포함하지 않음 → 유의미 ✅  
→ 신뢰구간에 0이 포함되면 "이 변수는 효과가 없을 수도 있다"는 의미  

4. 잔차 진단 (모델 가정 검토)   
Omnibus / Prob(Omnibus): 0.071  
잔차(오차)가 정규분포를 따르는지 검정   
→ 0.071 > 0.05 이므로 정규성 가정 만족 ✅   

Durbin-Watson: 1.362    
잔차의 자기상관(연속된 오차끼리 패턴이 있는지) 검정 
→ 기준: 2에 가까울수록 좋음 (0~4 범위)  
→ 1.362는 2보다 약간 작아서 약한 양의 자기상관 의심 
→ 시계열 데이터라면 주의 필요   

Jarque-Bera / Prob(JB): 0.132   
정규성 검정 (Omnibus와 비슷한 목적)  
→ 0.132 > 0.05 이므로 정규성 가정 만족 ✅   

Cond. No.: 588  
다중공선성 확인 (독립변수들끼리 서로 상관관계가 있는지) 
→ 기준: 30 이하면 문제없음, 30~1000은 주의, 1000 이상이면 심각  
→ 588이므로 다중공선성 의심 필요 ⚠️ 
→ hp와 wt가 서로 어느 정도 상관관계가 있을 가능성 있음  

5. 최종 요약    
항목	결과	해석    
R² = 0.827	✅ 좋음	모델이 데이터 82.7% 설명    
hp p=0.001	✅ 유의미	마력 높을수록 연비 소폭 감소    
wt p=0.000	✅ 유의미	무게 높을수록 연비 크게 감소    
정규성	✅ 만족	오차가 정규분포 따름    
다중공선성	⚠️ 주의	hp와 wt 간 상관관계 가능성  
결론: hp와 wt 두 변수로 mpg를 꽤 잘 예측하는 모델이며,  
특히 무게(wt) 가 연비에 미치는 영향이 가장 큼.  



Scikit-learn

In [ ]:
import sklearn as sk

from sklearn import svm
from sklearn import metrics

# 데이터 학습하기
# fit(학습 데이터, 학습 레이블)
clf = svm.SVC()
clf.fit([[0,0],
        [0,1],
        [1,0],
        [1,1]
        ],
        [0,1,1,0])

,C,1.0
,kernel,'rbf'
,degree,3
,gamma,'scale'
,coef0,0.0
,shrinking,True
,probability,False
,tol,0.001
,cache_size,200
,class_weight,None
,verbose,False


In [ ]:
# 데이터 예측하기

pre = clf.predict([[0,1],
                   [1,1]])
print(pre)

# 결과 확인
as_score = metrics.accuracy_score([1,0], pre)
print(f"정답률: {as_score}")

[1 0]
정답률: 1.0


In [22]:
from sklearn import svm
from sklearn import metrics
import pandas as pd

xor_data = [[0,0,0],
            [0,1,1],
            [1,0,1],
            [1,1,0]]
# 데이터 가공 - 학습을 위해 데이터와 레이블 분리
xor_df = pd.DataFrame(xor_data) # 매개변수: 입력 데이터
# xor_df.loc[전체데이터, 추출할 데이터]
# 학습 데이터
data = xor_df.loc[:,0:1]
#    0  1
# 0  0  0
# 1  0  1
# 2  1  0
# 3  1  1
# 레이블(정답)
label = xor_df.loc[:,2]
# 0    0
# 1    1
# 2    1
# 3    0
# ┌─────────────────────┐
# │ 입력1 │ 입력2 │ 정답 │
# │   0   │   0   │  0  │  ← 모델한테 0,0 주고 → 0 맞춰봐
# │   0   │   1   │  1  │  ← 모델한테 0,1 주고 → 1 맞춰봐
# │   1   │   0   │  1  │  ← 모델한테 1,0 주고 → 1 맞춰봐
# │   1   │   1   │  0  │  ← 모델한테 1,1 주고 → 0 맞춰봐
# └─────────────────────┘
#       ↓                        ↓
#     data                     label
#   (입력, X)                (정답, y)
clf = svm.SVC()
clf.fit(data, label)
pre = clf.predict(data)
print("예측결과:", pre)
as_score = metrics.accuracy_score(label,pre)
print(f"정답률: {as_score}")

예측결과: [0 1 1 0]
정답률: 1.0


scipy

In [23]:
import scipy as sp

from scipy.linalg import solve

A = [[3,1],[1,2]]
b = [9,8]
x = solve(A,b)
print(f"Solution: {x}")

Solution: [2. 3.]


In [ ]:
# 함수를 최소화하는 변수 값 구하기
from scipy.optimize import minimize

def f(x):
    return x**2 + 4*4 + 4

result = minimize(f, x0 = 0)
print(f"Optimal value: {result.x}")

Optimal value: [0.]


In [1]:
# 방정식의 근 찾기
from scipy.optimize import root
def equation(x):
    return x**2 - 4

sol = root(equation, x0=1)
print(f"Root: {sol.x}")

Root: [2.]


In [26]:
# 통계
# 기본 통계 계산(최소, 최대, 평균, 분산, 외도, 첨도)
from scipy.stats import describe

data = [1,2,3,4,5,6,7]
stats = describe(data)
print(stats)

DescribeResult(nobs=7, minmax=(np.int64(1), np.int64(7)), mean=np.float64(4.0), variance=np.float64(4.666666666666667), skewness=np.float64(0.0), kurtosis=np.float64(-1.25))


In [ ]:
# 희소 행렬
# 대부분의 값이 0으로 채워진 행렬
# 왜 따로 저장하는가?
# 행렬이 커질수록 0을 저장하는 게 메모리 낭비 임.

# 1000 x 1000 행렬에서 0이 99% 라면?
# → 일반 행렬: 1,000,000 개 저장
# → 희소 행렬: 0이 아닌 값 ~10,000 개만 저장  ← 훨씬 효율적
# 실제로 추천시스템, 자연어처리, 딥러닝에서 대부분의 데이터가 희소 행렬 형태임.

# 0이 많은 2차원 데이터를 0을 가지지 않는 요소만 표시하는 COO 포맷으로 변경
from scipy.sparse import csr_matrix
data = [[0,0,3],
        [4,0,0],
        [0,5,0]]

sparse_matrix = csr_matrix(data)
print(sparse_matrix)

# 출력 결과
# (0, 2)    3
# (1, 0)    4
# (2, 1)    5

# '(행, 열)  값' 형태로 0이 아닌 것만 출력함.

# (0, 2) → 0행 2열 → 값: 3
# (1, 0) → 1행 0열 → 값: 4
# (2, 1) → 2행 1열 → 값: 5

# 일반 행렬 저장방식       희소 행렬 저장방식
# ┌─────────────┐         ┌──────────────────┐
# │ 0  0  3     │         │ (0,2) → 3        │
# │ 4  0  0     │   →     │ (1,0) → 4        │
# │ 0  5  0     │         │ (2,1) → 5        │
# │ 9개 저장    │         │ 3개만 저장 ✅    │
# └─────────────┘         └──────────────────┘

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 3 stored elements and shape (3, 3)>
  Coords	Values
  (0, 2)	3
  (1, 0)	4
  (2, 1)	5
